version: '3'
services:
  web:
    image: orangehrm/orangehrm-environment-images:dev-php-latest-rhel-8
    ports:
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./config/mysql-client:/etc/mysql
      - ./config/apache2/sites-available:/etc/httpd/sites-available
      - ./config/apache2/cert:/etc/httpd/cert
      - ./logs/apache_logs:/var/log/httpd
      - /etc/localtime:/etc/localtime
      #- /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    restart: always
    hostname: orangehrm-dev-web_rhel
    container_name: dev_web_rhel
