version: '2'
services:
  nginx:
    image: orangehrm/orangehrm-environment-images:nginx
    ports:
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime
    privileged: true
    links:
      - db
    restart: always
    hostname: orangehrm-dev-web
    container_name: dev_web
