version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:dev-7.2-centos-orange
    ports:
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/mysql-client:/etc/mysql
      - ./config/apache2/sites-available:/etc/apache2/sites-available
      - ./config/apache2/cert:/etc/apache2/cert
      - ./logs/ubuntu_logs:/var/log/apache2
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    links:
      - db
    restart: always
    hostname: orangehrm-dev-web
    container_name: dev_web

  db:
    image: mysql:5.5
    expose:
      - "3306"
    volumes:
      - ./config/mysql-server:/etc/mysql
      - ./logs/mysql_logs:/var/log
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: always
    hostname: orangehrm-dev-db
    container_name: dev_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /etc/localtime:/etc/localtime
    links:
      - db
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db
    restart: always
    container_name: dev_phpmyadmin
