version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:dev-php-7.4-ubuntu-20.04
    ports:
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./config/mysql-client:/etc/mysql
      - ./config/apache2/sites-available:/etc/apache2/sites-available
      - ./config/apache2/cert:/etc/apache2/cert
      - ./logs/apache_logs:/var/log/apache
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    tty: true
    restart: always
    hostname: orangehrm-dev-web
    container_name: dev_web
