version: '2.2'
services:
  web_82_rh:
    image: orangehrm/dev-environment:rhel8-php8.2-latest
    volumes:
    - ./html:/var/www/html
    - ./config/web82rhel8/php/custom_php.ini:/etc/php.d/custom_php.ini
    - ./config/web82rhel8/mysql-client:/etc/mysql
    - ./config/web82rhel8/apache2/sites-available:/etc/httpd/sites-available
    - ./config/web82rhel8/apache2/sites-enabled:/etc/httpd/sites-enabled
    - ./config/web82rhel8/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
    - ./config/web82rhel8/apache2/cert:/etc/httpd/cert
    - ./logs/apache_logs/web82rhel8:/var/log/httpd
    - /etc/localtime:/etc/localtime
    privileged: true
    sysctls:
    - kernel.shmmax=67371264
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.182
    restart: always
    container_name: dev_web_82_rhel8   