FROM python:3.12

RUN mkdir -p ai_service/
WORKDIR /ai_service
#COPY ./codebase/ai-service-helpers/ /home/ai_service/
#RUN pip install -r requirements.txt
#RUN python3 -m spacy download en_core_web_lg

#ENTRYPOINT [ "python3 -m app.main" ]
CMD [ "sleep", "infinity" ]
